import json

log_path = '/Users/ayush/.gemini/antigravity-ide/brain/90ed6469-c013-4b31-a5d7-c4ce80e441fc/.system_generated/logs/transcript.jsonl'

longest_content = ""

with open(log_path, 'r') as f:
    for line in f:
        try:
            step = json.loads(line)
            if 'tool_calls' in step:
                for call in step['tool_calls']:
                    args = call.get('arguments', {})
                    # Look in write_to_file CodeContent
                    if 'CodeContent' in args and 'export default function SingaporeMapIcon' in args['CodeContent']:
                        content = args['CodeContent']
                        if len(content) > len(longest_content):
                            longest_content = content
                    
                    # Look in replace_file_content ReplacementContent
                    if 'ReplacementContent' in args and 'export default function SingaporeMapIcon' in args['ReplacementContent']:
                        content = args['ReplacementContent']
                        if len(content) > len(longest_content):
                            longest_content = content
                    
                    # Look in multi_replace_file_content
                    if 'ReplacementChunks' in args:
                        for chunk in args['ReplacementChunks']:
                            if 'ReplacementContent' in chunk and 'export default function SingaporeMapIcon' in chunk['ReplacementContent']:
                                content = chunk['ReplacementContent']
                                if len(content) > len(longest_content):
                                    longest_content = content
        except Exception as e:
            pass

if longest_content:
    with open('src/components/SingaporeMapIcon.jsx', 'w') as out:
        out.write(longest_content)
    print("Recovered! Length:", len(longest_content))
else:
    print("Not found in tool calls. It might have been generated by a local node script.")
